import * as FileSystem from 'expo-file-system';
import * as Sharing from 'expo-sharing';
import { supabase } from './supabase';

export interface ReportData {
  userName: string;
  email: string;
  period: string;
  totalFootprint: number;
  mealsFootprint: number;
  transportFootprint: number;
  energyFootprint: number;
  mealsCount: number;
  transportCount: number;
  energyCount: number;
  achievements: number;
  level: number;
}

function generateHTMLReport(data: ReportData): string {
  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>EcoTracker Report</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 40px;
      color: #333;
    }
    .header {
      text-align: center;
      color: #4CAF50;
      margin-bottom: 30px;
    }
    .section {
      margin: 20px 0;
      padding: 15px;
      border: 1px solid #ddd;
      border-radius: 8px;
    }
    .section h2 {
      color: #4CAF50;
      border-bottom: 2px solid #4CAF50;
      padding-bottom: 5px;
    }
    .stat {
      display: flex;
      justify-content: space-between;
      padding: 8px 0;
      border-bottom: 1px solid #eee;
    }
    .stat:last-child {
      border-bottom: none;
    }
    .stat-label {
      font-weight: bold;
    }
    .stat-value {
      color: #4CAF50;
    }
    .footer {
      text-align: center;
      margin-top: 40px;
      color: #666;
      font-size: 12px;
    }
    .total {
      background-color: #f0f8f0;
      padding: 20px;
      border-radius: 8px;
      text-align: center;
      margin: 20px 0;
    }
    .total h1 {
      color: #4CAF50;
      margin: 0;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>🌱 EcoTracker Report</h1>
    <p>${data.userName} (${data.email})</p>
    <p>${data.period}</p>
  </div>

  <div class="total">
    <h1>${data.totalFootprint.toFixed(2)} kg CO₂</h1>
    <p>Total Carbon Footprint</p>
  </div>

  <div class="section">
    <h2>📊 Breakdown by Category</h2>
    <div class="stat">
      <span class="stat-label">🍽️ Meals</span>
      <span class="stat-value">${data.mealsFootprint.toFixed(2)} kg CO₂</span>
    </div>
    <div class="stat">
      <span class="stat-label">🚗 Transport</span>
      <span class="stat-value">${data.transportFootprint.toFixed(2)} kg CO₂</span>
    </div>
    <div class="stat">
      <span class="stat-label">⚡ Energy</span>
      <span class="stat-value">${data.energyFootprint.toFixed(2)} kg CO₂</span>
    </div>
  </div>

  <div class="section">
    <h2>📈 Activity Summary</h2>
    <div class="stat">
      <span class="stat-label">Meals Logged</span>
      <span class="stat-value">${data.mealsCount}</span>
    </div>
    <div class="stat">
      <span class="stat-label">Trips Logged</span>
      <span class="stat-value">${data.transportCount}</span>
    </div>
    <div class="stat">
      <span class="stat-label">Energy Records</span>
      <span class="stat-value">${data.energyCount}</span>
    </div>
  </div>

  <div class="section">
    <h2>🏆 Achievements</h2>
    <div class="stat">
      <span class="stat-label">Badges Earned</span>
      <span class="stat-value">${data.achievements}</span>
    </div>
    <div class="stat">
      <span class="stat-label">Current Level</span>
      <span class="stat-value">${data.level}</span>
    </div>
  </div>

  <div class="footer">
    <p>Generated by EcoTracker on ${new Date().toLocaleDateString()}</p>
    <p>Keep tracking, keep improving! 🌍</p>
  </div>
</body>
</html>
  `;
}

export async function generatePDFReport(
  userId: string,
  startDate?: string,
  endDate?: string
): Promise<string | null> {
  try {
    // Get current user
    const { data: { user } } = await supabase.auth.getUser();
    const userEmail = user?.email || 'user@email.com';
    const userName = userEmail.split('@')[0];

    // Fetch data
    let mealsQuery = supabase.from('meals').select('*').eq('user_id', userId);
    let transportQuery = supabase.from('transport').select('*').eq('user_id', userId);
    let energyQuery = supabase.from('energy_consumption').select('*').eq('user_id', userId);

    if (startDate) {
      mealsQuery = mealsQuery.gte('date', startDate);
      transportQuery = transportQuery.gte('date', startDate);
      energyQuery = energyQuery.gte('date', startDate);
    }
    if (endDate) {
      mealsQuery = mealsQuery.lte('date', endDate);
      transportQuery = transportQuery.lte('date', endDate);
      energyQuery = energyQuery.lte('date', endDate);
    }

    const [mealsResult, transportResult, energyResult, achievementsResult] = await Promise.all([
      mealsQuery,
      transportQuery,
      energyQuery,
      supabase.from('achievements').select('*').eq('user_id', userId),
    ]);

    const meals = mealsResult.data || [];
    const transport = transportResult.data || [];
    const energy = energyResult.data || [];
    const achievements = achievementsResult.data || [];

    const reportData: ReportData = {
      userName,
      email: userEmail,
      period: startDate && endDate 
        ? `${startDate} to ${endDate}` 
        : 'All Time',
      totalFootprint: 
        meals.reduce((sum, m) => sum + m.carbon_footprint, 0) +
        transport.reduce((sum, t) => sum + t.carbon_footprint, 0) +
        energy.reduce((sum, e) => sum + e.carbon_footprint, 0),
      mealsFootprint: meals.reduce((sum, m) => sum + m.carbon_footprint, 0),
      transportFootprint: transport.reduce((sum, t) => sum + t.carbon_footprint, 0),
      energyFootprint: energy.reduce((sum, e) => sum + e.carbon_footprint, 0),
      mealsCount: meals.length,
      transportCount: transport.length,
      energyCount: energy.length,
      achievements: achievements.length,
      level: 1,
    };

    const html = generateHTMLReport(reportData);
    const fileName = `ecotracker_report_${Date.now()}.html`;
    const fileUri = `${FileSystem.documentDirectory}${fileName}`;

    await FileSystem.writeAsStringAsync(fileUri, html);

    if (await Sharing.isAvailableAsync()) {
      await Sharing.shareAsync(fileUri);
    }

    return fileUri;
  } catch (error) {
    console.error('Error generating PDF report:', error);
    return null;
  }
}
